app = "vox-pm-api"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "apps/api/Dockerfile"
  build_context = "apps/api"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "5s"
    method = "GET"
    path = "/docs"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
